config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  

  resources :accounts do
    collection do 
      get :delete_job_posts
      get :delete_non_clinical_job_posts
      get :delete_all_chats
    end
    resources :owners do 

    end
  end

  resources :owners do 
    resources :users, module: :owner_user do 
      resources :providers do 
        member do 
          get :send_message
        end
      end
      resources :job_posts
      resources :chats do 
        resources :messages
      end
    end
  end


  resources :users, module: :recruiter_user do 
    resources :job_posts do
      resources :chats do
        resources :messages do 
          collection do 
            get :add_office
          end
        end
      end
    end
  end

  resources :providers, module: :provider do 
    resources :job_posts do 
      member do 
        get :apply
      end
    end
    resources :non_clinical_job_posts do 
      member do 
        get :apply
      end
    end
    resources :chats do 
      resources :messages
    end
  end

  resources :vendors do 
    resources :users, module: :vendor_user do 
      resources :non_clinical_job_posts
      resources :chats do 
        resources :messages
      end
    end
  end

  root 'accounts#index'
end

app/models/job_post.rb
class JobPost < ApplicationRecord

  belongs_to :owner
  belongs_to :created_by_user, class_name: 'User', optional: true
  has_many :job_post_applications, dependent: :destroy
  has_many :chat_messages, through: :job_post_applications
  has_many :chats, through: :chat_messages

  def created_by_recruiter?
    !!self.created_by_user&.recruiter?
  end

  def applied?(provider)
    self.job_post_applications.where(provider: provider).exists?
  end

  def apply!(provider)
    jpa = self.job_post_applications.create(provider: provider)
    if self.created_by_recruiter?
      Mailbox.new(provider, jpa).send_message_to(self.owner.account, "I want to apply!", jpa)
    else
      Mailbox.new(provider).send_message_to(self.owner, "I want to apply!", jpa)
    end
  end
end

app/controllers/owner_user/job_posts_controller.rb
class OwnerUser::JobPostsController < OwnerUser::BaseController

  def index
    @job_posts = @current_owner.job_posts
  end

  def show
    @highlight_job_post = @current_owner.job_posts.where(id: params[:id]).first
    @job_posts = @current_owner.job_posts
    render :index
  end

  def new
    @job_post = @current_owner.job_posts.build
  end

  def create
    @job_post = @current_owner.job_posts.build(job_post_params)
    @job_post.created_by_user = @current_user
    @job_post.save!
    redirect_to action: :index
  end


  def job_post_params
    params.require(:job_post).permit(:name)
  end

end

app/controllers/provider/job_posts_controller.rb
class Provider::JobPostsController < Provider::BaseController

  def index
    @job_posts = JobPost.all
  end

  def show
    @highlight_job_post = JobPost.find(params[:id])
    @job_posts = JobPost.all
    render :index
  end

  def apply
    job_post = JobPost.find(params[:id])
    job_post.apply!(@current_provider)
    redirect_to action: :index
  end
end

app/controllers/recruiter_user/base_controller.rb
class RecruiterUser::BaseController < ApplicationController

  layout 'recruiter'

  before_action :load_user

  private

  def load_user
    @current_user = User.where(id: params[:user_id]).first
    @current_account = @current_user.account
  end

end

app/controllers/recruiter_user/job_posts_controller.rb
class RecruiterUser::JobPostsController < RecruiterUser::BaseController

  def index
    @job_posts = @current_account.job_posts
  end

  def show
    @job_post = @current_account.job_posts.where(id: params[:id]).first
  end
end

app/controllers/recruiter_user/messages_controller.rb
class RecruiterUser::MessagesController < RecruiterUser::BaseController

  def create
    @job_post = @current_account.job_posts.where(id: params[:job_post_id]).first
    chat = Chat.where(id: params[:chat_id]).first
    if @job_post.created_by_recruiter?
      chatbox = Chatbox.new(chat, @current_account)
      chatbox.send_proxy_message(@current_user, message_params[:content], nil)  
    else
      chatbox = Chatbox.new(chat, @job_post.owner)
      chatbox.send_proxy_message(@current_user, message_params[:content], nil)  
    end
    
    redirect_to user_job_post_path(@current_user, @job_post)
  end

  def edit
    @job_post = @current_account.job_posts.where(id: params[:job_post_id]).first
    @message = Chat::Message.find(params[:id])
  end

  def update
    @job_post = @current_account.job_posts.where(id: params[:job_post_id]).first
    @message = Chat::Message.find(params[:id])
    @message.update!(message_params)
    redirect_to user_job_post_path(@current_user, @job_post)
  end

  def add_office
    @job_post = @current_account.job_posts.where(id: params[:job_post_id]).first
    chat = Chat.where(id: params[:chat_id]).first
    chatbox = Chatbox.new(chat, @current_account)
    chatbox.add_chatter_as_member(@job_post.owner)
    redirect_to user_job_post_path(@current_user, @job_post)
  end

  def message_params
    params.require(:chat_message).permit(:content)
  end

end

app/views/recruiter_user/job_posts/_message_about.html.slim
- if message.about.present?
  div 
    | Message is about 
    = link_to "#{message.about.about_object.class.to_s.titleize}: #{message.about.about_name}", url_for([@job_post.owner, @current_user, message.about.about_object])

app/views/recruiter_user/job_posts/_message_edit_btn.html.slim
- if chatbox.editable?(message)
  = link_to "Edit", edit_user_job_post_chat_message_path( @current_user, @job_post, chatbox.chat, message)

app/views/recruiter_user/job_posts/index.html.slim
h1 Job Posts

table.table
  thead
    tr
      th Office
      th Created By
      th Name
      th Applicants
  tbody
    - @job_posts.each do |job_post|
      tr class=('border' if job_post == @highlight_job_post)
        td = job_post.owner.name
        td
          - if job_post.created_by_user.present?
            = job_post.created_by_user.name
          - else
            | Office
        td = link_to job_post.name, user_job_post_path(@current_user, job_post)
        td 
          - job_post.job_post_applications.each do |application|
            div = application.provider.name
          
        

app/views/recruiter_user/job_posts/show.html.slim
.row
  .col-sm-4
    h3 Job Post
    = "Office: #{@job_post.owner.name}"
    br
    br
    = "Job Name: #{@job_post.name}"
    br
    br
      | Applicants:
      - @job_post.job_post_applications.each do |application|
        div = application.provider.name


  .col-sm-8
    h4 Chats
    - @job_post.chats.each do |chat|
      - if @job_post.created_by_user&.recruiter?
        - chatbox = Chatbox.new(chat, @current_account)
      - else
        - chatbox = Chatbox.new(chat, @job_post.owner)
      .border
        = render '/shared/chats/messages', chatbox: chatbox
        = form_for Chat::Message.new, url: user_job_post_chat_messages_path(@current_user, @job_post, chat), method: :post  do |f|
          .row.p-2
            .col-sm-6
              = f.text_field :content, class: "form-control"
            .col-sm-3
              = f.submit "Send Message", class: "btn btn-primary"
            .col-sm-3
              - unless chatbox.is_chatter?(@job_post.owner)
                = link_to "Add Office to Chat", add_office_user_job_post_chat_messages_path(@current_user, @job_post, chat), class: "btn btn-success"
      br