config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  

  resources :accounts do
    collection do 
      get :delete_job_posts
      get :delete_non_clinical_job_posts
      get :delete_all_chats
    end
    resources :owners do 

    end
  end

  resources :owners do 
    resources :users, module: :owner_user do 
      resources :providers do 
        member do 
          get :send_message
        end
      end
      resources :job_posts
      resources :chats do 
        resources :messages
      end
    end
  end


  resources :users, module: :recruiter_user do 
    resources :job_posts do
      resources :chats do
        resources :messages do 
          collection do 
            get :add_office
          end
        end
      end
    end
  end

  resources :providers, module: :provider do 
    resources :job_posts do 
      member do 
        get :apply
      end
    end
    resources :non_clinical_job_posts do 
      member do 
        get :apply
      end
    end
    resources :chats do 
      resources :messages
    end
  end

  resources :vendors do 
    resources :users, module: :vendor_user do 
      resources :non_clinical_job_posts
      resources :chats do 
        resources :messages
      end
    end
  end

  root 'accounts#index'
end

app/models/non_clinical_job_post.rb
class NonClinicalJobPost < ApplicationRecord

  belongs_to :vendor
  has_many :non_clinical_job_applications, dependent: :destroy
  has_many :chat_messages, through: :non_clinical_job_applications
  has_many :chats, through: :chat_messages

  def applied?(provider)
    self.non_clinical_job_applications.where(provider: provider).exists?
  end

  def apply!(provider)
    ncja = self.non_clinical_job_applications.create(provider: provider)
    Mailbox.new(provider, ncja).send_message_to(self.vendor, "I want to apply!", ncja)
  end

end

app/controllers/provider/non_clinical_job_posts_controller.rb
class Provider::NonClinicalJobPostsController < Provider::BaseController

  def index
    @job_posts = NonClinicalJobPost.all
  end

  def show
    @highlight_job_post = NonClinicalJobPost.find(params[:id])
    @job_posts = NonClinicalJobPost.all
    render :index
  end

  def apply
    job_post = NonClinicalJobPost.find(params[:id])
    job_post.apply!(@current_provider)
    redirect_to action: :index
  end

end

app/controllers/vendor_user/base_controller.rb
class VendorUser::BaseController < ApplicationController

  layout 'vendor'

  before_action :load_vendor

  private

  def load_vendor
    @current_vendor = Vendor.find(params[:vendor_id])
    @current_user = @current_vendor.account.users.where(id: params[:user_id]).first
  end

end

app/controllers/vendor_user/chats_controller.rb
class VendorUser::ChatsController < VendorUser::BaseController

  def index
    @chats = @current_vendor.chats
    if params[:chat_id].present?
      @current_chat = @current_vendor.chats.where(id: params[:chat_id]).first
    else
      @current_chat = @current_vendor.chats.first
    end
    if @current_chat.present?
      @current_chatbox = Chatbox.new(@current_chat, @current_vendor)
      @current_chatbox.mark_all_messages_as_read!
    end
  end

  def send_message
    @chat = @current_vendor.chats.where(id: params[:id]).first
    chatbox = Chatbox.new(@chat, @current_vendor)
    chatbox.send_proxy_message(@current_user, message_params[:content], nil)
    redirect_to vendor_user_chats_path(@current_vendor, @current_user, chat_id: @chat.id)
  end

  def message_params
    params.require(:chat_message).permit(:content)
  end

end

app/controllers/vendor_user/messages_controller.rb
class VendorUser::MessagesController < VendorUser::BaseController

  def create
    @chat = @current_vendor.chats.where(id: params[:chat_id]).first
    chatbox = Chatbox.new(@chat, @current_vendor)
    chatbox.send_proxy_message(@current_user, message_params[:content], nil)
    redirect_to vendor_user_chats_path(@current_vendor, @current_user, chat_id: @chat.id)
  end

  def edit
    @message = Chat::Message.find(params[:id])
  end

  def update
    @message = Chat::Message.find(params[:id])
    @message.update!(message_params)
    redirect_to vendor_user_chats_path(@current_vendor, @current_user, chat_id: @message.chat_id)
  end

  def message_params
    params.require(:chat_message).permit(:content)
  end

end

app/controllers/vendor_user/non_clinical_job_posts_controller.rb
class VendorUser::NonClinicalJobPostsController < VendorUser::BaseController

  def index
    @job_posts = @current_vendor.non_clinical_job_posts
  end

  def show
    @job_post = @current_vendor.non_clinical_job_posts.where(id: params[:id]).first
  end

  def new
    @job_post = @current_vendor.non_clinical_job_posts.build
  end

  def create
    @job_post = @current_vendor.non_clinical_job_posts.build(non_clinical_job_posts_params)
    @job_post.save!
    redirect_to action: :index
  end


  def non_clinical_job_posts_params
    params.require(:non_clinical_job_post).permit(:name)
  end

end

app/views/vendor_user/non_clinical_job_posts/_message_about.html.slim
= render '/vendor_user/chats/message_about', message: message

app/views/vendor_user/non_clinical_job_posts/_message_edit_btn.html.slim
= render '/vendor_user/chats/message_edit_btn', chatbox: chatbox, message: message

app/views/vendor_user/non_clinical_job_posts/index.html.slim
h1 Non Clinical Job Posts
= link_to "New Non Clinical Job Post", new_vendor_user_non_clinical_job_post_path(@current_vendor, @current_user)
table.table
  thead
    tr
      th Name
      th Applicants
  tbody
    - @job_posts.each do |job_post|
      tr class=('border' if job_post == @highlight_job_post)
        td = link_to job_post.name, vendor_user_non_clinical_job_post_path(@current_vendor, @current_user, job_post)
        td 
          - job_post.non_clinical_job_applications.each do |application|
            div = application.provider.name
          
        

app/views/vendor_user/non_clinical_job_posts/new.html.slim
h1 New Non Clinical Job Post

= form_for @job_post, url: vendor_user_non_clinical_job_posts_path(@current_vendor, @current_user), method: :post  do |f|
      .row.p-2
        .col-sm-9
          = f.text_field :name, class: "form-control"
        .col-sm-3
          = f.submit "Create Job Post", class: "btn btn-primary"

app/views/vendor_user/non_clinical_job_posts/show.html.slim
.row
  .col-sm-4
    h3 Non Clinical Job Post
    = "Job Name: #{@job_post.name}"
    br
    br
      | Applicants:
      - @job_post.non_clinical_job_applications.each do |application|
        div = application.provider.name


  .col-sm-8
    h4 Chats
    - @job_post.chats.each do |chat|
      - chatbox = Chatbox.new(chat, @current_vendor)
      .border
        = render '/shared/chats/messages', chatbox: chatbox
        = form_for Chat::Message.new, url: vendor_user_chat_messages_path(@current_vendor, @current_user, chat), method: :post  do |f|
          .row.p-2
            .col-sm-9
              = f.text_field :content, class: "form-control"
            .col-sm-3
              = f.submit "Send Message", class: "btn btn-primary"
      br