config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  

  resources :accounts do
    collection do 
      get :delete_job_posts
      get :delete_non_clinical_job_posts
      get :delete_all_chats
    end
    resources :owners do 

    end
  end

  resources :owners do 
    resources :users, module: :owner_user do 
      resources :providers do 
        member do 
          get :send_message
        end
      end
      resources :job_posts
      resources :chats do 
        resources :messages
      end
    end
  end


  resources :users, module: :recruiter_user do 
    resources :job_posts do
      resources :chats do
        resources :messages do 
          collection do 
            get :add_office
          end
        end
      end
    end
  end

  resources :providers, module: :provider do 
    resources :job_posts do 
      member do 
        get :apply
      end
    end
    resources :non_clinical_job_posts do 
      member do 
        get :apply
      end
    end
    resources :chats do 
      resources :messages
    end
  end

  resources :vendors do 
    resources :users, module: :vendor_user do 
      resources :non_clinical_job_posts
      resources :chats do 
        resources :messages
      end
    end
  end

  root 'accounts#index'
end

app/models/account.rb
class Account < ApplicationRecord
  include ChatterCommons

  belongs_to :user, optional: true #Lead user
  has_many :users
  has_one :provider, dependent: :destroy, autosave: true # enable autosave in order to update profile completeness automatically.
  has_many :owners, dependent: :destroy, autosave: true
  has_many :job_posts, through: :owners
  has_one :vendor, dependent: :destroy, autosave: true

  def default_chat_member_group(chat)
    if provider?
      "provider_group"
    elsif vendor?
      "vendor_group"
    else
      "office_account_group"
    end
  end

  def provider?
    provider.present?
  end

  def owner?
    owners.any?
  end

  def vendor?
    vendor.present?
  end

  def type
    if self.owner?
      "Owner"
    elsif self.provider?
      "Provider"
    elsif self.vendor?
      "Vendor"
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = Account.order(name: :asc)
  end

  def show
    @account = Account.find(params[:id])
  end


  def delete_job_posts
    JobPost.all.each do |jp|
      jp.chats.each do |chat|
        chat.destroy
      end
      jp.destroy
    end
    redirect_to root_path
  end
      

  def delete_non_clinical_job_posts
    NonClinicalJobPost.all.each do |jp|
      jp.chats.each do |chat|
        chat.destroy
      end
      jp.destroy
    end
    redirect_to root_path
  end
  
  def delete_all_chats
    Chat.all.each do |chat|
      chat.destroy
    end
    redirect_to root_path
  end

end

app/views/accounts/index.html.slim
h1 Accounts

table.table
  thead
    tr
      th Name
      th Type
      th
  tbody
    - @accounts.each do |account|
      tr
        td = account.name
        td = account.type
        td = link_to "View Account", account_path(account)


h3 Ways to Start Chats
ol
  li Impersonate an Owner and click the Providers tab. Click “Send Hello message”
  li Impersonate Provider and click the Job Posts tab. Click “Apply to Job”
  li Impersonate Provider and click the Non Clinical Job Posts tab. Click “Apply to Job”

h3 Ways to view Chats
ol
  li Impersonate Owner and click the Chats tab
  li Impersonate Recruiter and click the DSO Recruiter Dashboard tab. Click into a Job Post
  li Impersonate Vendor and click the Job Post tab. Click into a Job Post
  li Impersonate Vendor and click on Chats tab

h3 Delete
div = link_to "Delete All Job Posts and associated Chats", delete_job_posts_accounts_path
div = link_to "Delete All Non Clinical Job Posts and associated Chats", delete_non_clinical_job_posts_accounts_path
div = link_to "Delete All Chats", delete_all_chats_accounts_path

app/views/accounts/show.html.slim
h1 = @account.name


- if @account.owner?
  h3 Owners
  table.table
    thead
      tr
        th Name
        th Users
    tbody
      - @account.owners.each do |owner|
        tr
          td = owner.name
          td
            - owner.users.each do |user|
              div = link_to "Impersonate #{user.name}", owner_user_job_posts_path(owner, user)

- elsif @account.provider?
  h3 Provider
  table.table
    thead
      tr
        th Name
        th Users
    tbody
      tr
        td = @account.provider.name
        td = link_to "Impersonate #{@account.user.name}", provider_job_posts_path(@account.provider)
- elsif @account.vendor?
  h3 Vendor
  table.table
    thead
      tr
        th Name
        th Users
    tbody
      tr
        td = @account.vendor.name
        td 
          - @account.users.each do |user|
            = link_to "Impersonate #{user.name}", vendor_user_non_clinical_job_posts_path(@account.vendor, user)